spring.application.name=telegram-listener

telegram.api-id=YOUR_API_ID
telegram.api-hash=YOUR_API_HASH
telegram.chat-id=YOUR_CHAT_ID


kafka.topic.telegram=YOUR-TOPIC
spring.kafka.bootstrap-servers=YOUR-KAFKA-IP
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=tg:YOUR_MAPPING