spring.application.name=telegram-listener

telegram.api-id=YOUR_API_ID
telegram.api-hash=YOUR_API_HASH
telegram.chat-id=YOUR_CHAT_ID,YOUR_CHAT_ID,OR_MORE


kafka.topic.telegram=telegram-message-topic
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=tg:com.example.telegramlistener.client.dto.TgMessageDto